[package]
edition = "2018"
name = "bentobox"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]

[dependencies]
pnet = "*"
tun = "*"
log = "*"
failure = "*"
clap = "*"
libc = "*"
env_logger = "*"